add class Order
yauhen14/Pizza pull request #4
Opened 2022-08-19 15:52 UTC by yauhen14

add class Order
add enum OrderStatus

2022-08-19 16:55 UTC, galkha commented on src/order/Order.java
> +    private Map<String, Double> recipes;
В этой мапе значение - количество пицц в заказе, целое число, вроде бы. А тип Double?

2022-08-20 06:29 UTC, SviatlanaYatsuk commented on src/order/Order.java
> +    public Order(LocalDate date, String clientId, OrderStatus orderStatus, Map<String, Byte> recipes) {
Может если дата формирования заказа текущая, то ее во входящих параметрах прописывать не нужно? просто this.date = LocalDate.now();

2022-08-22 11:29 UTC, JuliyaBunas requested changes

2022-08-22 11:29 UTC, JuliyaBunas commented on src/order/Order.java
> +        this.orderStatus = orderStatus;
Думаю при создании объекта статус всегда будет NEW

2022-08-22 11:30 UTC, JuliyaBunas commented on src/order/OrderStatus.java
> +public enum OrderStatus {
Отличное применение enum-а

2022-08-22 16:32 UTC, merged